
sparkMaster: spark://ec2-54-205-168-96.compute-1.amazonaws.com:7077
# test: 10

# server:
#   requestLog:
#     timeZone: UTC
#     appenders:
#       - type: file
#         currentLogFilename: ./logs/requests.log
#         threshold: ALL
#         archive: true
#         archivedLogFilenamePattern: ./logs/requests.%d.log.gz
#         archivedFileCount: 5
#
